**Introdução ao Numpy**

In [17]:
import numpy as np
matriz = np.array([[1,2,3],[4,5,6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

**Tipos**

In [18]:
type(matriz)

numpy.ndarray

In [19]:
matriz.dtype.name

'int32'

**Dimensões do DataFrama**

In [20]:
matriz.shape

(2, 3)

In [22]:
matriz.size

6

**Criando valores (passo a passo, espaçados ou randômicos)**

In [24]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [25]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [28]:
np.random.randint(0,30,7)

array([10, 21, 21,  8, 27,  8,  0])

In [31]:
matriz2 = np.random.randint(0,30,6).reshape(3,2)
matriz2

array([[ 6, 10],
       [18,  1],
       [ 4,  8]])

In [40]:
matriz.argmax() 

5

In [41]:
matriz.max()

6

In [42]:
matriz.mean()

3.5

**Desvio Padrão**

In [43]:
matriz.std()

1.707825127659933

In [47]:
matriz3= np.array([[2,4,6],[8,7,1]])

In [48]:
matriz3.shape

(2, 3)

**Operadores**

In [49]:
matriz + matriz3

array([[ 3,  6,  9],
       [12, 12,  7]])

In [50]:
matriz.shape

(2, 3)

In [51]:
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
matriz * matriz3

array([[ 2,  8, 18],
       [32, 35,  6]])

In [53]:
matriz ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

**Selação e ALteração de Valores**

In [54]:
matriz[1][1]

5

In [55]:
matriz3[0][2]

6

In [56]:
matriz3[matriz3>4]

array([6, 8, 7])

In [58]:
matriz3[1][matriz3[1]>4]

array([8, 7])

In [59]:
matriz3[1][0]=16

In [60]:
matriz3

array([[ 2,  4,  6],
       [16,  7,  1]])

In [61]:
matriz3 = np.insert(matriz3,1,[0,0,1],axis=0)
matriz3

array([[ 2,  4,  6],
       [ 0,  0,  1],
       [16,  7,  1]])

In [62]:
matriz.shape

(2, 3)

In [63]:
matriz3.shape


(3, 3)